export const user = [
  {
    id: 1,
    name: "Shuvro",
    profileImage: "/images/profile.svg", 
    followers: "5.7K",
    following: "100",
    isFollowing: false,
    ownedStamps: 5, // Number of owned stamps
    onSaleStamps: 2, // Number of stamps on sale
  },
  {
    id: 2,
    name: "Gunjan",
    profileImage: "/images/profile.svg",
    followers: "2.4K",
    following: "200",
    isFollowing: true,
    ownedStamps: 3,
    onSaleStamps: 1,
  },
  {
    id: 3,
    name: "Aryan",
    profileImage: "/images/profile.svg",
    followers: "10K",
    following: "180",
    isFollowing: false,
    ownedStamps: 8,
    onSaleStamps: 4,
  },
  {
    id: 4,
    name: "Sarthak",
    profileImage: "/images/profile.svg",
    followers: "3.2K",
    following: "350",
    isFollowing: true,
    ownedStamps: 6,
    onSaleStamps: 3,
  },
  {
    id: 5,
    name: "Vivek",
    profileImage: "/images/profile.svg",
    followers: "6.9K",
    following: "290",
    isFollowing: false,
    ownedStamps: 7,
    onSaleStamps: 2,
  },
  {
    id: 6,
    name: "Dev",
    profileImage: "/images/profile.svg",
    followers: "1.5K",
    following: "50",
    isFollowing: true,
    ownedStamps: 4,
    onSaleStamps: 0,
  },
  {
    id: 7,
    name: "Emmanuel",
    profileImage: "/images/profile.svg",
    followers: "8.1K",
    following: "95",
    isFollowing: false,
    ownedStamps: 9,
    onSaleStamps: 5,
  },
  {
    id: 8,
    name: "Sarah",
    profileImage: "/images/profile.svg",
    followers: "4.3K",
    following: "250",
    isFollowing: true,
    ownedStamps: 3,
    onSaleStamps: 1,
  },
  {
    id: 9,
    name: "Kashish",
    profileImage: "/images/profile.svg",
    followers: "7.6K",
    following: "400",
    isFollowing: false,
    ownedStamps: 10,
    onSaleStamps: 4,
  },
  {
    id: 10,
    name: "Maseera",
    profileImage: "/images/profile.svg",
    followers: "9K",
    following: "120",
    isFollowing: true,
    ownedStamps: 2,
    onSaleStamps: 1,
  },
];
