export const dummyStampsOwned = [
  {
    id: 1,
    collectibletitle: 'Legendary Poets of Odisha',
    image: '/images/image0.jpg',
    minting: 'Now',
    price: 500,
    rarity: 55,
    description: 'A collection celebrating the legendary poets of Odisha.',
    creator: 'Ashley',
    owner: 'Aleena',
    releaseDate: '2023-01-15',
    shortTitle: 'Legendary Poets',
    numOfReviews: 3945,
    likes: 1250,
  },
  {
    id: 2,
    collectibletitle: 'Gopabandhu Das',
    image: '/images/image1.jpg',
    minting: 'Now',
    price: 300,
    rarity: 45,
    description: 'Commemorating the esteemed Gopabandhu Das.',
    creator: 'Vandita',
    owner: 'Samiksha',
    releaseDate: '2022-11-05',
    shortTitle: 'Gopabandhu Das',
    numOfReviews: 1573,
    likes: 845,
  },
  {
    id: 3,
    collectibletitle: 'North-East Orchids Collection Postcards - Set of 10',
    image: '/images/postcards3.jpg',
    minting: 'In 1 week',
    price: 349,
    rarity: 65,
    description: 'A collection of 6 postcards showcasing traditional dance forms of India.',
    creator: 'Ira',
    owner: 'Sneha',
    releaseDate: '2023-08-01',
    shortTitle: 'Traditional Dance Forms',
    numOfReviews: 980,
    likes: 1032,
  },
  {
    id: 4,
    collectibletitle: '100th Birth Anniversary of Karpoor Thakur',
    image: '/images/image3.jpg',
    minting: 'Now',
    price: 600,
    rarity: 70,
    description: 'Celebrating the 100th birth anniversary of Karpoor Thakur.',
    creator: 'Daisman',
    owner: 'Vineet',
    releaseDate: '2023-04-01',
    shortTitle: 'Karpoor Thakur Anniversary',
    numOfReviews: 892,
    likes: 980,
  },
  {
    id: 5,
    collectibletitle: 'Halloluck 64 Pcs Vintage Retro Classic Movie Postcards',
    image: '/images/postcards5.jpg',
    minting: 'Now',
    price: 349,
    rarity: 50,
    description: 'A set of 10 postcards featuring monuments from North-East India.',
    creator: 'Gunjan',
    owner: 'Ashwani',
    releaseDate: '2022-12-20',
    shortTitle: 'North-East Monument',
    numOfReviews: 643,
    likes: 721,
  },
  {
    id: 6,
    collectibletitle: '64 Pcs 2 Set Vintage Retro Old Travel Postcards',
    image: '/images/postcards6.jpg',
    minting: 'Now',
    price: 349,
    rarity: 55,
    description: 'A collection of 8 watercolor postcards featuring botanical illustrations.',
    creator: 'Abhidha',
    owner: 'Prasukh',
    releaseDate: '2022-09-15',
    shortTitle: 'Botanicals Water Colour',
    numOfReviews: 1254,
    likes: 843,
  },
  {
    id: 7,
    collectibletitle: 'North-East Birds Collection Postcards - Set of 10',
    image: '/images/postcards4.jpg',
    minting: 'Now',
    price: 359,
    rarity: 65,
    description: 'Set of 6 postcards showcasing objects from Assam.',
    creator: 'Yana',
    owner: 'Ghania',
    releaseDate: '2023-02-28',
    shortTitle: 'Objects of Assam',
    numOfReviews: 1789,
    likes: 956,
  },
  {
    id: 8,
    collectibletitle: 'Srila Bhaktisiddhanta Saraswati Prabhupada',
    image: '/images/image2.jpg',
    minting: 'Now',
    price: 250,
    rarity: 60,
    description: 'Honoring Srila Bhaktisiddhanta Saraswati Prabhupada.',
    creator: 'Shuvro',
    owner: 'Sachin',
    releaseDate: '2022-08-10',
    shortTitle: 'Srila Bhaktisiddhanta',
    numOfReviews: 2100,
    likes: 1123,
  },
  {
    id: 9,
    collectibletitle: 'Mountain Peaks of the Himalayas - Scenic Postcard',
    image: '/images/postcards7.jpg',
    minting: 'Now',
    price: 299,
    rarity: 60,
    description: 'Set of 5 postcards featuring the highest peaks of India.',
    creator: 'Mira',
    owner: 'Shaan',
    releaseDate: '2023-07-12',
    shortTitle: 'Mountain Peaks',
    numOfReviews: 1305,
    likes: 911,
  },
  {
    id: 10,
    collectibletitle: 'India Postcard Pack (Pack of 14)',
    image: '/images/postcards2.jpg',
    minting: 'Now',
    price: 399,
    rarity: 50,
    description: 'Set of 8 postcards featuring historical landmarks across India.',
    creator: 'Anaya',
    owner: 'Rahul',
    releaseDate: '2022-10-10',
    shortTitle: 'Historical Landmarks',
    numOfReviews: 1370,
    likes: 1089,
  },
  {
    id: 11,
    collectibletitle: 'Divine Greetings From India Post card - Set of 9 Postcard',
    image: '/images/postcards1.jpg',
    minting: 'In 1 week',
    price: 349,
    rarity: 65,
    description: 'A collection of 6 postcards showcasing traditional dance forms of India.',
    creator: 'Ira',
    owner: 'Sneha',
    releaseDate: '2023-08-01',
    shortTitle: 'Traditional Dance Forms',
    numOfReviews: 980,
    likes: 1001,
  }
]

export const dummyStampsCollections = [
  {
    id: 8,
    collectibletitle: 'Gandhi’s Visionary Letters',
    image: 'https://cdn.collectorbazar.com/products/india-mahatma-gandhi-visionary-picture-postcard-issued-by-gandhi-ashram-amhmedabad-nc0138-410627-1.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 250,
    rarity: 60,
    description: 'A collection of Gandhi’s personal letters that shaped India’s future.',
    creator: 'Shuvro',
    owner: 'Sachin',
    releaseDate: '2022-08-10',
    shortTitle: 'Gandhi Letters',
    numOfReviews: 2100,
    likes: 1123,
  },
  {
    id: 6,
    collectibletitle: 'Historic Monuments of India',
    image: 'https://m.media-amazon.com/images/I/A1JYEkMZqcL.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 349,
    rarity: 55,
    description: 'Postcards featuring iconic monuments from ancient and modern India.',
    creator: 'Abhidha',
    owner: 'Prasukh',
    releaseDate: '2022-09-15',
    shortTitle: 'Monuments of India',
    numOfReviews: 1254,
    likes: 843,
  },
  {
    id: 3,
    collectibletitle: 'Buddhist Heritage Sites Postcards',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT0kCvZk-j3_ipJ1bfsDYIEpwZGgPw4Ycljg&s', // Replace with actual Google image URL
    minting: 'In 1 week',
    price: 349,
    rarity: 65,
    description: 'Set of postcards depicting famous Buddhist heritage sites in India.',
    creator: 'Ira',
    owner: 'Sneha',
    releaseDate: '2023-08-01',
    shortTitle: 'Buddhist Heritage',
    numOfReviews: 980,
    likes: 1032,
  },
  {
    id: 4,
    collectibletitle: 'Freedom Fighters of India',
    image: 'https://philabasket.com/wp-content/uploads/2022/02/PC10-%E2%80%93-Picture-Postcards-on-125th-Birth-anniversary-of-Netaji-Subhash-Chandra-Bose-23-Jan-2022-Set-of-6-Buy-India-Stamp-PhilaBasket-1-scaled.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 600,
    rarity: 70,
    description: 'Celebrating the legacy of India’s greatest freedom fighters.',
    creator: 'Daisman',
    owner: 'Vineet',
    releaseDate: '2023-04-01',
    shortTitle: 'Freedom Fighters',
    numOfReviews: 892,
    likes: 980,
  },
  {
    id: 5,
    collectibletitle: 'Cultural Festivals of India',
    image: 'https://stampwala.com/wp-content/uploads/2024/03/111-35.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 349,
    rarity: 50,
    description: 'Postcards showcasing the vibrant festivals celebrated across India.',
    creator: 'Gunjan',
    owner: 'Ashwani',
    releaseDate: '2022-12-20',
    shortTitle: 'Festivals of India',
    numOfReviews: 643,
    likes: 721,
  },
  {
    id: 7,
    collectibletitle: 'Exotic Wildlife of India',
    image: 'https://www.philindiastamps.com/cdn/shop/products/1_5ed638a7-4b7d-40c9-a909-a7fec380beff_200x200@2x.jpg?v=1535040294', // Replace with actual Google image URL
    minting: 'Now',
    price: 359,
    rarity: 65,
    description: 'Postcards featuring India’s rare and exotic wildlife species.',
    creator: 'Yana',
    owner: 'Ghania',
    releaseDate: '2023-02-28',
    shortTitle: 'Wildlife of India',
    numOfReviews: 1789,
    likes: 956,
  },
  {
    id: 9,
    collectibletitle: 'Taj Mahal - A Wonder of the World',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Stamp_of_India_-_1949_-_Colnect_986620_-_1_-_Taj_Mahal_Agra.jpeg', // Replace with actual Google image URL
    minting: 'Now',
    price: 299,
    rarity: 60,
    description: 'A postcard collection showcasing the grandeur of the Taj Mahal.',
    creator: 'Mira',
    owner: 'Shaan',
    releaseDate: '2023-07-12',
    shortTitle: 'Taj Mahal',
    numOfReviews: 1305,
    likes: 911,
  },
  {
    id: 10,
    collectibletitle: 'Incredible India Postcard Pack',
    image: 'https://www.ruandchai.com/cdn/shop/products/IMG_0182-2_1200x1200.jpg?v=1617725026', // Replace with actual Google image URL
    minting: 'Now',
    price: 399,
    rarity: 50,
    description: 'A beautiful collection of India’s diverse cultures and landscapes.',
    creator: 'Anaya',
    owner: 'Rahul',
    releaseDate: '2022-10-10',
    shortTitle: 'Incredible India',
    numOfReviews: 1370,
    likes: 1089,
  },
  {
    id: 11,
    collectibletitle: 'Sacred Temples of India',
    image: 'https://i0.wp.com/indianhobbyclub.com/wp-content/uploads/2023/05/Image-454-1.jpg?fit=538%2C628&ssl=1', // Replace with actual Google image URL
    minting: 'In 1 week',
    price: 349,
    rarity: 65,
    description: 'Postcards featuring renowned temples from across the country.',
    creator: 'Ira',
    owner: 'Sneha',
    releaseDate: '2023-08-01',
    shortTitle: 'Sacred Temples',
    numOfReviews: 980,
    likes: 1001,
  },
  {
    id: 2,
    collectibletitle: 'Sculptures of Ancient India',
    image: 'https://storage.googleapis.com/hipstamp/p/6d443aa0705279ccd4b0b5cd07dcc90c-300.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 300,
    rarity: 45,
    description: 'A set of postcards showcasing India’s ancient sculptures and art.',
    creator: 'Vandita',
    owner: 'Samiksha',
    releaseDate: '2022-11-05',
    shortTitle: 'Ancient Sculptures',
    numOfReviews: 1573,
    likes: 845,
  },
  {
    id: 1,
    collectibletitle: 'Royal Palaces of India',
    image: 'https://stampwala.com/wp-content/uploads/2019/10/111-118.jpg', // Replace with actual Google image URL
    minting: 'Now',
    price: 500,
    rarity: 55,
    description: 'Postcards highlighting the stunning royal palaces of India.',
    creator: 'Ashley',
    owner: 'Aleena',
    releaseDate: '2023-01-15',
    shortTitle: 'Royal Palaces',
    numOfReviews: 3945,
    likes: 1250,
  },
];

export const dummyStampsOnSale = [
  {
    id: 11,
    collectibletitle: 'Divine Greetings From India Post card - Set of 9 Postcard',
    image: '/images/postcards1.jpg',
    minting: 'In 1 week',
    price: 349,
    rarity: 65,
    description: 'A collection of 6 postcards showcasing traditional dance forms of India.',
    creator: 'Ira',
    owner: 'Sneha',
    releaseDate: '2023-08-01',
    shortTitle: 'Traditional Dance Forms',
    numOfReviews: 980,
    likes: 1001,
  },
  {
    id: 5,
    collectibletitle: 'Halloluck 64 Pcs Vintage Retro Classic Movie Postcards',
    image: '/images/postcards5.jpg',
    minting: 'Now',
    price: 349,
    rarity: 50,
    description: 'A set of 10 postcards featuring monuments from North-East India.',
    creator: 'Gunjan',
    owner: 'Ashwani',
    releaseDate: '2022-12-20',
    shortTitle: 'North-East Monument',
    numOfReviews: 643,
    likes: 721,
  },
  {
    id: 7,
    collectibletitle: 'North-East Birds Collection Postcards - Set of 10',
    image: '/images/postcards4.jpg',
    minting: 'Now',
    price: 359,
    rarity: 65,
    description: 'Set of 6 postcards showcasing objects from Assam.',
    creator: 'Yana',
    owner: 'Ghania',
    releaseDate: '2023-02-28',
    shortTitle: 'Objects of Assam',
    numOfReviews: 1789,
    likes: 956,
  },
  {
    id: 9,
    collectibletitle: 'Mountain Peaks of the Himalayas - Scenic Postcard',
    image: '/images/postcards7.jpg',
    minting: 'Now',
    price: 299,
    rarity: 60,
    description: 'Set of 5 postcards featuring the highest peaks of India.',
    creator: 'Mira',
    owner: 'Shaan',
    releaseDate: '2023-07-12',
    shortTitle: 'Mountain Peaks',
    numOfReviews: 1305,
    likes: 911,
  },
  {
    id: 10,
    collectibletitle: 'India Postcard Pack (Pack of 14)',
    image: '/images/postcards2.jpg',
    minting: 'Now',
    price: 399,
    rarity: 50,
    description: 'Set of 8 postcards featuring historical landmarks across India.',
    creator: 'Anaya',
    owner: 'Rahul',
    releaseDate: '2022-10-10',
    shortTitle: 'Historical Landmarks',
    numOfReviews: 1370,
    likes: 1089,
  },
  {
    id: 8,
    collectibletitle: 'Srila Bhaktisiddhanta Saraswati Prabhupada',
    image: '/images/image2.jpg',
    minting: 'Now',
    price: 250,
    rarity: 60,
    description: 'Honoring Srila Bhaktisiddhanta Saraswati Prabhupada.',
    creator: 'Shuvro',
    owner: 'Sachin',
    releaseDate: '2022-08-10',
    shortTitle: 'Srila Bhaktisiddhanta',
    numOfReviews: 2100,
    likes: 1123,
  },
  {
    id: 2,
    collectibletitle: 'Gopabandhu Das',
    image: '/images/image1.jpg',
    minting: 'Now',
    price: 300,
    rarity: 45,
    description: 'Commemorating the esteemed Gopabandhu Das.',
    creator: 'Vandita',
    owner: 'Samiksha',
    releaseDate: '2022-11-05',
    shortTitle: 'Gopabandhu Das',
    numOfReviews: 1573,
    likes: 845,
  },
  {
    id: 1,
    collectibletitle: 'Legendary Poets of Odisha',
    image: '/images/image0.jpg',
    minting: 'Now',
    price: 500,
    rarity: 55,
    description: 'A collection celebrating the legendary poets of Odisha.',
    creator: 'Ashley',
    owner: 'Aleena',
    releaseDate: '2023-01-15',
    shortTitle: 'Legendary Poets',
    numOfReviews: 3945,
    likes: 1250,
  },
]