export const trendingData = {
    '1H': [
        {
            collector: 'Priyanshu',
            img: '/profile/5.svg',
            items: 150,
            id: 1,
            collectibletitle: 'Botanical Water Colour Collection',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 459,
            rarity: 75,
            description: 'A collection of beautiful botanical watercolor paintings.',
            creator: 'Arya',
            owner: 'Anand',
            releaseDate: '2023-03-20',
            shortTitle: 'Botanical Collection',
            numOfReviews: 3456,
            likes: 950,
            followers: "5.7K",
            following: "100",
            isFollowing: false,
            ownedStamps: 5,
            onSaleStamps: 5
        },
        {
            collector: 'Husain',
            img: '/profile/1.svg',
            items: 129,
            id: 2,
            collectibletitle: 'Legend Of Odisha',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 599,
            rarity: 45,
            description: 'A tribute to the legendary history of Odisha.',
            creator: 'Zara',
            owner: 'Husain',
            releaseDate: '2022-11-01',
            shortTitle: 'Legend Of Odisha',
            numOfReviews: 2045,
            likes: 1050,
            followers: "2.4K",
            following: "200",
            isFollowing: true,
            ownedStamps: 11,
            onSaleStamps: 8
        },
        {
            collector: 'Anand',
            img: '/profile/2.svg',
            items: 115,
            id: 3,
            collectibletitle: 'Aptos',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 249,
            rarity: 60,
            description: 'A special collection of Aptos stamps.',
            creator: 'Aryan',
            owner: 'Priyanshu',
            releaseDate: '2024-02-05',
            shortTitle: 'Aptos Collection',
            numOfReviews: 1876,
            likes: 800,
            followers: "10K",
            following: "180",
            isFollowing: false,
            ownedStamps: 8,
            onSaleStamps: 4
        },
        {
            collector: 'James',
            img: '/profile/3.svg',
            items: 103,
            id: 4,
            collectibletitle: 'Gangadhar Meher',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 349,
            rarity: 50,
            description: 'Celebrating the work of Gangadhar Meher.',
            creator: 'Aryan',
            owner: 'James',
            releaseDate: '2023-09-10',
            shortTitle: 'Gangadhar Meher',
            numOfReviews: 2567,
            likes: 950,
            followers: "3.2K",
            following: "350",
            isFollowing: true,
            ownedStamps: 6,
            onSaleStamps: 3
        },
        {
            collector: 'Sami',
            img: '/profile/4.svg',
            items: 111,
            id: 5,
            collectibletitle: 'Abbakka Chowta',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 409,
            rarity: 55,
            description: 'A collection dedicated to Abbakka Chowta.',
            creator: 'Ria',
            owner: 'Sami',
            releaseDate: '2023-07-15',
            shortTitle: 'Abbakka Chowta',
            numOfReviews: 1200,
            likes: 600,
            followers: "6.9K",
            following: "290",
            isFollowing: false,
            ownedStamps: 7,
            onSaleStamps: 2
        },
        {
            collector: 'Pandey',
            img: '/profile/5.svg',
            items: 105,
            id: 6,
            collectibletitle: 'Karpoori Thakur',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 139,
            rarity: 80,
            description: 'Honoring the legacy of Karpoori Thakur.',
            creator: 'Vaibhav',
            owner: 'Pandey',
            releaseDate: '2023-05-10',
            shortTitle: 'Karpoori Thakur',
            numOfReviews: 850,
            likes: 300,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 0
        },
        {
            collector: 'Jumal',
            img: '/profile/6.svg',
            items: 102,
            id: 7,
            collectibletitle: 'New Arrival',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 549,
            rarity: 65,
            description: 'Featuring new arrivals in the collectible market.',
            creator: 'Emma',
            owner: 'Jumal',
            releaseDate: '2024-01-01',
            shortTitle: 'New Arrival',
            numOfReviews: 980,
            likes: 750,
            followers: "8.1K",
            following: "95",
            isFollowing: false,
            ownedStamps: 9,
            onSaleStamps: 5
        }
        // Add more collectors similarly for '1H' time frame if needed
    ],
    '1D': [
        {
            collector: 'Husain',
            img: '/profile/1.svg',
            items: 98,
            id: 1,
            collectibletitle: 'Royal Heritage',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 599,
            rarity: 60,
            description: 'The latest addition to the stamp collection world.',
            creator: 'Maya',
            owner: 'Anand',
            releaseDate: '2023-04-12',
            shortTitle: 'New Arrival',
            numOfReviews: 4523,
            likes: 1320,
            followers: "5.7K",
            following: "100",
            isFollowing: false,
            ownedStamps: 5,
            onSaleStamps: 2
        },
        {
            collector: 'James',
            img: '/profile/2.svg',
            items: 130,
            id: 2,
            collectibletitle: 'Legend Of Odisha',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 610,
            rarity: 45,
            description: 'A tribute to the legendary history of Odisha.',
            creator: 'Zara',
            owner: 'Husain',
            releaseDate: '2022-11-01',
            shortTitle: 'Legend Of Odisha',
            numOfReviews: 2045,
            likes: 1050,
            followers: "2.4K",
            following: "200",
            isFollowing: true,
            ownedStamps: 11,
            onSaleStamps: 1
        },
        {
            collector: 'Priyanshu',
            img: '/profile/3.svg',
            items: 120,
            id: 3,
            collectibletitle: 'New Arrival',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 499,
            rarity: 55,
            description: 'A special collection celebrating royal heritage.',
            creator: 'Liam',
            owner: 'Priyanshu',
            releaseDate: '2024-03-22',
            shortTitle: 'Royal Heritage',
            numOfReviews: 1890,
            likes: 920,
            followers: "10K",
            following: "180",
            isFollowing: false,
            ownedStamps: 8,
            onSaleStamps: 4
        },
        {
            collector: 'Anand',
            img: '/profile/4.svg',
            items: 105,
            id: 4,
            collectibletitle: 'Historic Moments',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 389,
            rarity: 70,
            description: 'A collection of historic moments captured in stamps.',
            creator: 'Abhishek',
            owner: 'James',
            releaseDate: '2023-10-05',
            shortTitle: 'Historic Moments',
            numOfReviews: 2740,
            likes: 1120,
            followers: "3.2K",
            following: "350",
            isFollowing: true,
            ownedStamps: 6,
            onSaleStamps: 3
        },
        {
            collector: 'Sami',
            img: '/profile/5.svg',
            items: 115,
            id: 5,
            collectibletitle: 'Ancient Scripts',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price: 359,
            rarity: 50,
            description: 'A collection featuring ancient scripts.',
            creator: 'Shuvro',
            owner: 'Sami',
            releaseDate: '2024-02-18',
            shortTitle: 'Ancient Scripts',
            numOfReviews: 1530,
            likes: 670,
            followers: "6.9K",
            following: "290",
            isFollowing: false,
            ownedStamps: 7,
            onSaleStamps: 2
        },
        {
            collector: 'Jumal',
            img: '/profile/6.svg',
            items: 108,
            id: 6,
            collectibletitle: 'Modern Art',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 359,
            rarity: 65,
            description: 'A collection showcasing modern art.',
            creator: 'Ethan',
            owner: 'Pandey',
            releaseDate: '2023-12-01',
            shortTitle: 'Modern Art',
            numOfReviews: 1320,
            likes: 550,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 1
        },
        {
            collector: 'Pandey',
            img: '/profile/7.svg',
            items: 108,
            id: 7,
            collectibletitle: 'Karpoori Thakur',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 359,
            rarity: 65,
            description: 'A collection showcasing modern art.',
            creator: 'Manvi',
            owner: 'Pandey',
            releaseDate: '2023-12-01',
            shortTitle: 'Modern Art',
            numOfReviews: 1320,
            likes: 550,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 1
        }
        // Add more collectors similarly for '1D' time frame if needed
    ],
    '7D': [
        {
            collector: 'James',
            img: '/profile/8.svg',
            items: 112,
            id: 1,
            collectibletitle: 'Botanical Water Colour Collection',
            image: '/profile/botanical.svg',
            minting: 'Now',
            price:  459,
            rarity: 75,
            description: 'A collection of beautiful botanical watercolor paintings.',
            creator: 'Ashley',
            owner: 'James',
            releaseDate: '2023-03-20',
            shortTitle: 'Botanical Collection',
            numOfReviews: 3456,
            likes: 950,
            followers: "3.2K",
            following: "350",
            isFollowing: true,
            ownedStamps: 6,
            onSaleStamps: 3
        },
        {
            collector: 'Husain',
            img: '/profile/1.svg',
            items: 99,
            id: 6,
            collectibletitle: 'Karpoori Thakur',
            image: '/profile/botanical.svg',
            minting: 'Exclusive',
            price: 150,
            rarity: 25,
            description: 'A rare and valuable collection featuring Karpoori Thakur.',
            creator: 'Tina',
            owner: 'Husain',
            releaseDate: '2022-05-10',
            shortTitle: 'Karpoori Thakur',
            numOfReviews: 999,
            likes: 480,
            followers: "2.4K",
            following: "200",
            isFollowing: true,
            ownedStamps: 3,
            onSaleStamps: 1
        },
        {
            collector: 'Priyanshu',
            img: '/profile/2.svg',
            items: 104,
            id: 7,
            collectibletitle: 'Ancient Scripts',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 359,
            rarity: 50,
            description: 'A collection featuring ancient scripts from various civilizations.',
            creator: 'Pravin',
            owner: 'Priyanshu',
            releaseDate: '2024-02-18',
            shortTitle: 'Ancient Scripts',
            numOfReviews: 1530,
            likes: 670,
            followers: "10K",
            following: "180",
            isFollowing: false,
            ownedStamps: 8,
            onSaleStamps: 4
        },
        {
            collector: 'Sami',
            img: '/profile/3.svg',
            items: 123,
            id: 8,
            collectibletitle: 'Historic Moments',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 399,
            rarity: 60,
            description: 'A collection capturing historic moments from around the world.',
            creator: 'Aryan',
            owner: 'Sami',
            releaseDate: '2023-10-05',
            shortTitle: 'Historic Moments',
            numOfReviews: 2740,
            likes: 1120,
            followers: "6.9K",
            following: "290",
            isFollowing: false,
            ownedStamps: 7,
            onSaleStamps: 2
        },
        {
            collector: 'Pandey',
            img: '/profile/4.svg',
            items: 110,
            id: 9,
            collectibletitle: 'Ancient Scripts Collection',
            image: '/profile/botanical.svg',
            minting: 'Exclusive',
            price: 359,
            rarity: 65,
            description: 'A unique collection of modern art stamps.',
            creator: 'Karuna',
            owner: 'Pandey',
            releaseDate: '2023-12-01',
            shortTitle: 'Modern Art',
            numOfReviews: 1320,
            likes: 550,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 1
        },
        {
            collector: 'Anand',
            img: '/profile/6.svg',
            items: 108,
            id: 6,
            collectibletitle: 'Modern Art',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 359,
            rarity: 65,
            description: 'A collection showcasing modern art.',
            creator: 'Ethan',
            owner: 'Pandey',
            releaseDate: '2023-12-01',
            shortTitle: 'Modern Art',
            numOfReviews: 1320,
            likes: 550,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 1
        },
        {
            collector: 'Jumal',
            img: '/profile/5.svg',
            items: 108,
            id: 7,
            collectibletitle: 'Chandshekhar',
            image: '/profile/botanical.svg',
            minting: 'Limited',
            price: 359,
            rarity: 65,
            description: 'A collection showcasing modern art.',
            creator: 'Aleena',
            owner: 'Pandey',
            releaseDate: '2023-12-01',
            shortTitle: 'Modern Art',
            numOfReviews: 1320,
            likes: 550,
            followers: "1.5K",
            following: "50",
            isFollowing: true,
            ownedStamps: 4,
            onSaleStamps: 1
        }
        // Add more collectors similarly for '7D' time frame if needed
    ],
    '30D': [
    {
        collector: 'Jumal',
        img: '/profile/james.svg',
        items: 118,
        id: 7,
        collectibletitle: 'Chandshekhar',
        image: '/profile/botanical.svg',
        minting: 'Exclusive',
        price: 999,
        rarity: 85,
        description: 'A detailed collection featuring the life of Chandrashekhar.',
        creator: 'Pravin',
        owner: 'Jumal',
        releaseDate: '2021-10-02',
        shortTitle: 'Chandshekhar',
        numOfReviews: 4783,
        likes: 1540,
        followers: "8.1K",
        following: "95",
        isFollowing: false,
        ownedStamps: 9,
        onSaleStamps: 5
    },
    {
        collector: 'Priyanshu',
        img: '/profile/james.svg',
        items: 113,
        id: 8,
        collectibletitle: 'Botanical Water Colour Collection',
        image: '/profile/botanical.svg',
        minting: 'Now',
        price: 459,
        rarity: 75,
        description: 'A collection of beautiful botanical watercolor paintings.',
        creator: 'Gunjan',
        owner: 'Priyanshu',
        releaseDate: '2023-03-20',
        shortTitle: 'Botanical Collection',
        numOfReviews: 3456,
        likes: 950,
        followers: "10K",
        following: "180",
        isFollowing: false,
        ownedStamps: 8,
        onSaleStamps: 4
    },
    {
        collector: 'Sami',
        img: '/profile/james.svg',
        items: 120,
        id: 9,
        collectibletitle: 'Historic Moments',
        image: '/profile/botanical.svg',
        minting: 'Limited',
        price: 399,
        rarity: 60,
        description: 'A collection capturing historic moments from around the world.',
        creator: 'Sarthak',
        owner: 'Sami',
        releaseDate: '2023-10-05',
        shortTitle: 'Historic Moments',
        numOfReviews: 2740,
        likes: 1120,
        followers: "6.9K",
        following: "290",
        isFollowing: false,
        ownedStamps: 7,
        onSaleStamps: 2
    },
    {
        collector: 'Anand',
        img: '/profile/james.svg',
        items: 115,
        id: 10,
        collectibletitle: 'Royal Heritage',
        image: '/profile/botanical.svg',
        minting: 'Exclusive',
        price: 375,
        rarity: 65,
        description: 'A unique collection of modern art stamps.',
        creator: 'Shuvro',
        owner: 'Pandey',
        releaseDate: '2023-12-01',
        shortTitle: 'Modern Art',
        numOfReviews: 1320,
        likes: 550,
        followers: "1.5K",
        following: "50",
        isFollowing: true,
        ownedStamps: 4,
        onSaleStamps: 1
    },
    {
        collector: 'James',
        img: '/profile/james.svg',
        items: 108,
        id: 6,
        collectibletitle: 'Legend Of Odisha',
        image: '/profile/botanical.svg',
        minting: 'Limited',
        price: 599,
        rarity: 65,
        description: 'A collection showcasing modern art.',
        creator: 'Neha',
        owner: 'Pandey',
        releaseDate: '2023-12-01',
        shortTitle: 'Modern Art',
        numOfReviews: 1320,
        likes: 550,
        followers: "1.5K",
        following: "50",
        isFollowing: true,
        ownedStamps: 4,
        onSaleStamps: 1
    },
    {
        collector: 'Husain',
        img: '/profile/james.svg',
        items: 108,
        id: 7,
        collectibletitle: 'New Arrival',
        image:'/profile/botanical.svg',
        minting: 'Limited',
        price: 359,
        rarity: 65,
        description: 'A collection showcasing modern art.',
        creator: 'Aryan',
        owner: 'Pandey',
        releaseDate: '2023-12-01',
        shortTitle: 'Modern Art',
        numOfReviews: 1320,
        likes: 550,
        followers: "1.5K",
        following: "50",
        isFollowing: true,
        ownedStamps: 4,
        onSaleStamps: 1
    },
    {
        collector: 'Pandey',
        img: '/profile/james.svg',
        items: 108,
        id: 7,
        collectibletitle: 'Ancient Scripts Collection',
        image:'/profile/botanical.svg',
        minting: 'Limited',
        price: 359,
        rarity: 65,
        description: 'A collection showcasing modern art.',
        creator: 'Shuvro',
        owner: 'Pandey',
        releaseDate: '2023-12-01',
        shortTitle: 'Modern Art',
        numOfReviews: 1320,
        likes: 550,
        followers: "1.5K",
        following: "50",
        isFollowing: true,
        ownedStamps: 4,
        onSaleStamps: 1
    }
    // Add more collectors similarly for '30D' time frame if needed
    ]
};